//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.tblAreas_Servicios = new HashSet<tblAreas_Servicios>();
            this.tblServicios = new HashSet<tblServicio>();
        }
    
        public int idArea { get; set; }
        public string nombreArea { get; set; }
        public System.DateTime horaInicio { get; set; }
        public System.DateTime horaFinal { get; set; }
        public int idColaborador { get; set; }
        public int idAula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAreas_Servicios> tblAreas_Servicios { get; set; }
        public virtual tblAula tblAula { get; set; }
        public virtual tblColaboradore tblColaboradore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServicio> tblServicios { get; set; }
    }
}
