//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCita
    {
        public int idCita { get; set; }
        public int idColaborador { get; set; }
        public int idHorario { get; set; }
        public int idSemanas { get; set; }
        public int idDias { get; set; }
    
        public virtual tblColaboradore tblColaboradore { get; set; }
        public virtual tblDías tblDías { get; set; }
        public virtual tblHorario tblHorario { get; set; }
        public virtual tblSemana tblSemana { get; set; }
    }
}
