//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColaboradore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblColaboradore()
        {
            this.tblAreas = new HashSet<tblArea>();
            this.tblCitas = new HashSet<tblCita>();
            this.tblEventos = new HashSet<tblEvento>();
        }
    
        public int idColaborador { get; set; }
        public string nombreColaborador { get; set; }
        public string telefonoColaborador { get; set; }
        public string correoColaborador { get; set; }
        public System.DateTime horarioInicio { get; set; }
        public System.DateTime horaFin { get; set; }
        public string contraseniaColaborador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArea> tblAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCita> tblCitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvento> tblEventos { get; set; }
    }
}
