//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticia
    {
        public int idNoticias { get; set; }
        public string noticiasTitulo { get; set; }
        public string noticiasTexto { get; set; }
        public int idNivel { get; set; }
    
        public virtual tblNivel tblNivel { get; set; }
    }
}
