//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServicio
    {
        public int idservicios { get; set; }
        public string serviciosNombre { get; set; }
        public int idArea { get; set; }
    
        public virtual tblArea tblArea { get; set; }
    }
}
