//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoyolaMovilBDEntities : DbContext
    {
        public LoyolaMovilBDEntities()
            : base("name=LoyolaMovilBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAnio> tblAnios { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblAreas_Servicios> tblAreas_Servicios { get; set; }
        public virtual DbSet<tblAula> tblAulas { get; set; }
        public virtual DbSet<tblCita> tblCitas { get; set; }
        public virtual DbSet<tblColaboradore> tblColaboradores { get; set; }
        public virtual DbSet<tblDías> tblDías { get; set; }
        public virtual DbSet<tblEdificio> tblEdificios { get; set; }
        public virtual DbSet<tblEvento> tblEventos { get; set; }
        public virtual DbSet<tblHorario> tblHorarios { get; set; }
        public virtual DbSet<tblNivel> tblNivels { get; set; }
        public virtual DbSet<tblNoticia> tblNoticias { get; set; }
        public virtual DbSet<tblSemana> tblSemanas { get; set; }
        public virtual DbSet<tblServicio> tblServicios { get; set; }
        public virtual DbSet<tblTipoAula> tblTipoAulas { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
